name: Create AWS Res by Tf

on:
  workflow_dispatch:
    inputs:
      resource:
        description: "Select resource"
        required: true
        type: choice
        options:
          - ec2
          - s3

      confirm:
        description: "Type YES to confirm"
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Safety Check
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "YES" ]; then
            echo "Confirmation failed. Type YES to proceed."
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Apply
        run: terraform apply -auto-approve \
          -var="resource_type=${{ github.event.inputs.resource }}" \
          -var="env=${{ github.event.inputs.environment }}"
